threads:
    parsing: 1
    trimmomatic: 4
    picard: 4 # Insert size
    spades: 12
    pileup: 1 # Generate contig metrics
    multiqc: 1
    checkm: 4 
    quast: 4
    fastqc: 1
    kraken2: 8

mem_gb:
    parsing: 4
    trimmomatic: 12
    picard: 12
    spades: 100
    pileup: 100
    multiqc: 8
    checkm: 12
    quast: 8
    fastqc: 8
    kraken2: 32